### ISSUE TITLE
UI Updates

### ISSUE THREAD

**Issue by vonderborch** [vonderborch/SolutionCreator#4]
- **Create Solution From Template** Button: Remove
- **Cancel** Button: Rename and update functionality to be a "Reset" button 
- Make Template Info section thinner, but take up teh whole vertical space
- Make Solution Templates section take up the full vertical space
- Add button to take user to the templates directory
- Add button to documentation on using the tool
- Add button to documentation on making a new template
- Add button to check for updates
- Make New Solution Configuration section thinner

**Comment by aseemsahoo** [comment]
Please assign me this issue.
