### ISSUE TITLE
Improve Startup Performance

### ISSUE THREAD

**Issue by vonderborch** [vonderborch/SolutionCreator#8]
Update call to fetch the user's current full name to be async or something to improve startup times: https://github.com/vonderborch/SolutionCreator/blob/dbedb0d074b2800c421979a6b4b940b79439e6e9/SolutionCreatorApp/MainForm.cs#L71

We can prevent solutions from being created while we wait for this info to be populated (maybe have an indicator that we're fetching it somewhere though!).

**Comment by aseemsahoo** [comment]
Please assign this issue to me.
